version: '2'
services:

  consul:
    image: consul
    ports:
      - "6500:8500"
    environment:
      - CONSUL_BIND_INTERFACE=eth0

  zipkin:
    image: "openzipkin/zipkin"
    ports:
      - "6411:9411"

  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50005"]
    ports:
      - "60005:50005"

  redisdb:
    image: redis
    restart: always

  ecoa:
    image: shawoo/node:edge
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - APP_ID=ecoa
      - APP_PORT=3303
      - TZ=Asia/Shanghai
    ports:
      - 3701:3500
    depends_on:
      - consul
      - redisdb
      - placement
      - zipkin
      
  ecob:
    image: shawoo/node:edge
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - APP_ID=ecob
      - APP_PORT=3303
      - TZ=Asia/Shanghai
    ports:
      - 3702:3500
    depends_on:
      - consul
      - redisdb
      - placement
      - zipkin
        
  ecoc:
    image: shawoo/java8:edge
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - APP_ID=ecoc
      - APP_PORT=8080
      - TZ=Asia/Shanghai
    ports:
      - 3703:3500
    depends_on:
      - consul
      - redisdb
      - placement
      - zipkin

  ecod:
    image: shawoo/dotnet6:edge
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - APP_ID=ecod
      - APP_PORT=5248
      - TZ=Asia/Shanghai
    ports:
      - 3704:3500
    depends_on:
      - consul
      - redisdb
      - placement
      - zipkin

  yao:
    image: shawoo/yao:edge-0.10.1
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /opt/s3/xyz/yao:/opt/app
    environment:
      - APP_ID=yao
      - APP_PORT=5099
      - TZ=Asia/Shanghai
    ports:
      - 5099:5099
    depends_on:
      #- consul
      - redisdb
      - placement
      - zipkin

  fast:
    image: shawoo/fastapi:edge
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - APP_ID=fast
      - APP_PORT=8000
      - TZ=Asia/Shanghai
    ports:
      - 8989:8888
    depends_on:
      #- consul
      - redisdb
      - placement
      - zipkin

  strapi:
    build: ./strapi
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      #- ./fast.sh:/opt/api/start.sh
    privileged: true
    environment:
      - VER=0.1
      - APP_ID=strapi
      - APP_PORT=1337
      - TZ=Asia/Shanghai
    ports:
      - 1337:1337
    depends_on:
      #- consul
      - redisdb
      - placement
      - zipkin
  nstr:
    image: shawoo/nstr:edge
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./nstr/C4/:/opt/bpm/C4/
      #- ./fast.sh:/opt/api/start.sh
    privileged: true
    environment:
      - APP_ID=nstr
      - APP_PORT=3303
      - TZ=Asia/Shanghai
    ports:
      - 2337:1337
    depends_on:
      - redisdb
      - placement
      - zipkin

  dash:
    image: shawoo/dash:edge
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      #- ./fast.sh:/opt/api/start.sh
    privileged: true
    environment:
      - VER=0.6
      - APP_ID=dash
      - APP_PORT=8050
      - TZ=Asia/Shanghai
    ports:
      - 8889:8888
      - 8050:8050
    depends_on:
      #- consul
      - redisdb
      - placement
      - zipkin

